# file: C:\Users\ADITI\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\scipy\integrate\_quadpack_py.py
# hypothesis_version: 6.135.14

[0.0, 5e-29, 1.49e-08, 'IntegrationWarning', 'Unknown error.', 'alg', 'alg-log', 'alg-loga', 'alg-logb', 'cauchy', 'cos', 'dblquad', 'depth', 'epsabs', 'epsrel', 'imag', 'neval', 'nquad', 'points', 'quad', 'real', 'sin', 'tplquad', 'unexpected kwargs', 'unknown']