# file: C:\Users\ADITI\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\numpy\lib\_datasource.py
# hypothesis_version: 6.135.14

['+', '..', '.bz2', '.gz', '.lzma', '.xz', '/', 'Invalid mode: %r', '_istmpdest', 'b', 'bz2', 'numpy', 'r', 't', 'w', 'wb']