# file: C:\Users\ADITI\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\_pytest\debugging.py
# hypothesis_version: 6.135.14

['--pdb', '--pdbcls', '--trace', '.', ':', '>', 'PDB continue', 'Quitting debugger', '__tracebackhide__', 'all', 'captured ', 'capturemanager', 'entering PDB', 'general', 'global', 'header', 'log', 'modulename:classname', 'pdbinvoke', 'pdbtrace', 'post_mortem', 'runcall', 'set_trace', 'stderr', 'stdout', 'store_true', 'terminalreporter', 'trace', 'traceback', 'usepdb', 'usepdb_cls']