# file: C:\Users\ADITI\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\scipy\optimize\_direct_py.py
# hypothesis_version: 6.135.14

[1e-16, 1e-06, 0.0001, -100, 1000, 'Forced stop', 'Invalid arguments', 'Out of memory', 'direct', 'maxfun is too large', 'maxfun must be > 0.', 'maxiter must be > 0.']