# file: C:\Users\ADITI\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\scipy\special\__init__.py
# hypothesis_version: 6.135.14

['SpecialFunctionError', 'ellip_harm', 'ellip_harm_2', 'ellip_normal', 'lambertw', 'log_softmax', 'logsumexp', 'multigammaln', 'nt', 'softmax', 'spherical_in', 'spherical_jn', 'spherical_kn', 'spherical_yn']